import React, { Component } from "react"

import Squiggle from "../design_el/squiggle"
import Line from "../design_el/line"
class PhilosophiesPageholder extends Component {
  state = {}
  render() {
    return (
      <div className="pageholder philosophies-page">
        <h1>Philosophies</h1>
        <Squiggle length="200px"></Squiggle>
        {/* <p className="small-caps rust construction">
          // This site is still under construction.
        </p> */}
        <p className="small-caps">
          <span className="rust">//</span> Everyone wants to feel seen, heard, understood, and like they belong.
        </p>
        <h2>
        Real, honest, values-driven cultural fit is a no-brainer for long-term success. Here's what I'm about:
        </h2>

        <ol className="philosophies">
          <li>
            <h3 className="philosophy-title">Functional, but fun.</h3>
            <p>
              You won't have fun if something isn't functional, and you won't want to use something that's not fun. This circular and highly contextual debate is central to any designer's life, and it's one I like to strike the balance of through user testing, ye ol' business-school matrixing, and a lot of experimentation. Though I'm a big believer in "less, but better <em>- Rams</em>," sometimes you gotta have fun. Remixing basic office snacks into gastronomic delights notwithstanding 🍫🍩🍿🍁🥥
            </p>
          </li>
          <li>
            <h3 className="philosophy-title">All together now.</h3>
            <p>
              Are accessibility, diversity, and inclusion fundamental values in your life and work? Is this something you try to be better at every day? If so, let's be work pals. In my experience, designing anything with these as guiding principles results in a clearer, cleaner, and better product. I've recently been turned onto the concept of an "edge case often solves the main case" approach. Just like how mobile-first has become the predominant design paradigm to solve for an ever-increasing array of devices, I'd like to champion accessibility-first as the next paradigm that ensures <em>all</em> users can use, enjoy, and benefit from products equitably.
            </p>
          </li>
          <li>
            <h3 className="philosophy-title">Mise en place.</h3>
            <p>
              IMHO, the recent emergence and popularity of design systems is a response to some of chaos and silly tech debt that's generated by certain ubiquitous methodologies. There's definitely a time and place to get scrappy: but there's also a lot of value in developing systems and principles that help mitigate decision fatigue and allow designers and developers freedom to create and innovate independently and still deliver a cohesive end result. I get great satisfaction from successfully negotiating the requirements of business, design, and development into such systems, often employing super weird metaphorical storytelling techniques that require a "stick with me to the end" preface.
            </p>
          </li>
          <li>
            <h3 className="philosophy-title">Laterally (not literally).</h3>
            <p>
              Whether using spreadsheet skills from my finance days to generate code, or applying backcountry survival skills to project management, I'm a big believer in the value of diverse experiences and in finding patterns, parallels, and solutions in unexpected places. I think it's important to listen to, learn from, and try new things regularly to stay inspired, identify opportunities for improvement, and thusly become a better designer, professional, and person. You gotta shake it up and include diverse and wildcard perspectives into user interviews, design sprints, and life in general. You have to flex that imagination. You can expect some fun ideas from someone nicknamed скриня (translation: box?) for being predictably outside-the-box. </p>
          </li>
          <li>
            <h3 className="philosophy-title">
              Keep asking "why?" 
            </h3>
            <p>
              It may be cliché, but it's also a really powerful feature of mine. I think understanding motives, goals, and context are extremely important in making sure you're solving for problems that actually exist, in ways that actually work and satisfy the objectives of as many stakeholders as possible. I'm hungry to not just learn, but to understand the why behind decisions, opinions, and objectives. Authenticity, clarity, and respectful candor are traits I hope to share with future colleagues and clients. 
            </p>
          </li>
        </ol>

        <hr />
        <h3>Skillsets</h3>
        <div className="skillset-container">
          <div className="skillset">
            <h4>DESIGN</h4>
            <ul>
              <li></li>
            </ul>
          </div>
          <div className="skillset">
            <h4>CODE</h4>
            <ul>
              <li>TOOLS</li>
            </ul>
          </div>
          <div className="skillset">
            <h4>Other</h4>
            <ul>
              <li></li>
            </ul>
          </div>
        </div>
        <p className="small-caps">...And so much more!!!</p>
        <h4>
          Fluent in Ukrainian, can survive comfortably and bountifully in the
          wilderness while I apply first aid, music nerd, bike nerd, printmaker
          & artist, amateur chef and novice sourdough head.
        </h4>
      </div>
    )
  }
}

export default PhilosophiesPageholder
